name: "🐛 Bug Report"
description: "Report a bug found during testing"
labels: ["bug"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: "Testing Phase"
      options:
        - "Phase 0 - Avalonia Migration"
        - "Phase 1 - Core Editing"
        - "Phase 2 - Resource Integration"
        - "Phase 3 - Script & Parameters"
        - "Phase 4 - UI/UX Enhancements"
        - "Phase 5 - Advanced Visualization"
        - "Phase 6 - Testing & Validation"
        - "Unphased"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Critical - Crash/data loss"
        - "High - Core functionality broken"
        - "Medium - Feature impacted"
        - "Low - Minor/cosmetic"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Brief description of the bug"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps"
      placeholder: |
        1. Open [file]
        2. Select [node]
        3. Perform [action]
        4. Expected: [behavior]
        5. Actual: [behavior]
    validations:
      required: true

  - type: checkboxes
    id: testing
    attributes:
      label: "Testing Notes"
      options:
        - label: "Reproduces consistently"
        - label: "Aurora compatibility issue"
        - label: "Round-trip tested"
        - label: "Multiple files tested"

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      value: |
        - OS: Windows
        - Build: [commit hash]
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Logs, screenshots, or related issues"
