name: "🐛 Bug Report"
description: "Report a bug or issue"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Report bugs with clear reproduction steps and expected behavior.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Clear description of the bug"
      placeholder: "Brief summary of the issue..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps"
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Open dialog file
        2. Select node
        3. Perform action
        4. Observe issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should happen"
      placeholder: "The application should..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happens"
      placeholder: "Instead, the application..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Severity of the issue"
      options:
        - "Critical - Crash/data loss"
        - "High - Core functionality broken"
        - "Medium - Feature impacted"
        - "Low - Minor/cosmetic"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "System information"
      value: |
        - OS: Windows
        - Version: [version or commit hash]
        - Branch: [branch name]
      render: markdown

  - type: checkboxes
    id: testing
    attributes:
      label: "Testing Details"
      options:
        - label: "Reproduces consistently"
        - label: "Tested with multiple files"
        - label: "Aurora Engine compatibility issue"
        - label: "Data corruption risk"

  - type: textarea
    id: logs
    attributes:
      label: "Logs/Screenshots"
      description: "Error messages, stack traces, or screenshots"
      placeholder: "Paste logs or attach screenshots..."

  - type: textarea
    id: related
    attributes:
      label: "Related Issues"
      description: "Links to related issues or PRs"
      placeholder: "Relates to #123, blocks #456"
