# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginHostStub(object):
    """Plugin host service (C# → Python communication)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/parley.plugin.PluginHost/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/parley.plugin.PluginHost/Initialize',
                request_serializer=plugin__pb2.InitializeRequest.SerializeToString,
                response_deserializer=plugin__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/parley.plugin.PluginHost/Shutdown',
                request_serializer=plugin__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=plugin__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class PluginHostServicer(object):
    """Plugin host service (C# → Python communication)
    """

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Lifecycle events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=plugin__pb2.InitializeRequest.FromString,
                    response_serializer=plugin__pb2.InitializeResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=plugin__pb2.ShutdownRequest.FromString,
                    response_serializer=plugin__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.PluginHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.PluginHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginHost(object):
    """Plugin host service (C# → Python communication)
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.PluginHost/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.PluginHost/Initialize',
            plugin__pb2.InitializeRequest.SerializeToString,
            plugin__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.PluginHost/Shutdown',
            plugin__pb2.ShutdownRequest.SerializeToString,
            plugin__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PluginStub(object):
    """Plugin service (Python → C# communication)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/parley.plugin.Plugin/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.OnDialogChanged = channel.unary_unary(
                '/parley.plugin.Plugin/OnDialogChanged',
                request_serializer=plugin__pb2.DialogChangedEvent.SerializeToString,
                response_deserializer=plugin__pb2.EventResponse.FromString,
                _registered_method=True)
        self.OnNodeSelected = channel.unary_unary(
                '/parley.plugin.Plugin/OnNodeSelected',
                request_serializer=plugin__pb2.NodeSelectedEvent.SerializeToString,
                response_deserializer=plugin__pb2.EventResponse.FromString,
                _registered_method=True)


class PluginServicer(object):
    """Plugin service (Python → C# communication)
    """

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnDialogChanged(self, request, context):
        """Lifecycle notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnNodeSelected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'OnDialogChanged': grpc.unary_unary_rpc_method_handler(
                    servicer.OnDialogChanged,
                    request_deserializer=plugin__pb2.DialogChangedEvent.FromString,
                    response_serializer=plugin__pb2.EventResponse.SerializeToString,
            ),
            'OnNodeSelected': grpc.unary_unary_rpc_method_handler(
                    servicer.OnNodeSelected,
                    request_deserializer=plugin__pb2.NodeSelectedEvent.FromString,
                    response_serializer=plugin__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin(object):
    """Plugin service (Python → C# communication)
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.Plugin/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnDialogChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.Plugin/OnDialogChanged',
            plugin__pb2.DialogChangedEvent.SerializeToString,
            plugin__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnNodeSelected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.Plugin/OnNodeSelected',
            plugin__pb2.NodeSelectedEvent.SerializeToString,
            plugin__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AudioServiceStub(object):
    """Audio service (Plugin → Host)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayAudio = channel.unary_unary(
                '/parley.plugin.AudioService/PlayAudio',
                request_serializer=plugin__pb2.PlayAudioRequest.SerializeToString,
                response_deserializer=plugin__pb2.PlayAudioResponse.FromString,
                _registered_method=True)
        self.StopAudio = channel.unary_unary(
                '/parley.plugin.AudioService/StopAudio',
                request_serializer=plugin__pb2.StopAudioRequest.SerializeToString,
                response_deserializer=plugin__pb2.StopAudioResponse.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Audio service (Plugin → Host)
    """

    def PlayAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAudio,
                    request_deserializer=plugin__pb2.PlayAudioRequest.FromString,
                    response_serializer=plugin__pb2.PlayAudioResponse.SerializeToString,
            ),
            'StopAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudio,
                    request_deserializer=plugin__pb2.StopAudioRequest.FromString,
                    response_serializer=plugin__pb2.StopAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Audio service (Plugin → Host)
    """

    @staticmethod
    def PlayAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.AudioService/PlayAudio',
            plugin__pb2.PlayAudioRequest.SerializeToString,
            plugin__pb2.PlayAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.AudioService/StopAudio',
            plugin__pb2.StopAudioRequest.SerializeToString,
            plugin__pb2.StopAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UIServiceStub(object):
    """UI service (Plugin → Host)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShowNotification = channel.unary_unary(
                '/parley.plugin.UIService/ShowNotification',
                request_serializer=plugin__pb2.ShowNotificationRequest.SerializeToString,
                response_deserializer=plugin__pb2.ShowNotificationResponse.FromString,
                _registered_method=True)
        self.ShowDialog = channel.unary_unary(
                '/parley.plugin.UIService/ShowDialog',
                request_serializer=plugin__pb2.ShowDialogRequest.SerializeToString,
                response_deserializer=plugin__pb2.ShowDialogResponse.FromString,
                _registered_method=True)
        self.RegisterPanel = channel.unary_unary(
                '/parley.plugin.UIService/RegisterPanel',
                request_serializer=plugin__pb2.RegisterPanelRequest.SerializeToString,
                response_deserializer=plugin__pb2.RegisterPanelResponse.FromString,
                _registered_method=True)
        self.UpdatePanelContent = channel.unary_unary(
                '/parley.plugin.UIService/UpdatePanelContent',
                request_serializer=plugin__pb2.UpdatePanelContentRequest.SerializeToString,
                response_deserializer=plugin__pb2.UpdatePanelContentResponse.FromString,
                _registered_method=True)
        self.ClosePanel = channel.unary_unary(
                '/parley.plugin.UIService/ClosePanel',
                request_serializer=plugin__pb2.ClosePanelRequest.SerializeToString,
                response_deserializer=plugin__pb2.ClosePanelResponse.FromString,
                _registered_method=True)
        self.GetTheme = channel.unary_unary(
                '/parley.plugin.UIService/GetTheme',
                request_serializer=plugin__pb2.GetThemeRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetThemeResponse.FromString,
                _registered_method=True)
        self.GetSpeakerColors = channel.unary_unary(
                '/parley.plugin.UIService/GetSpeakerColors',
                request_serializer=plugin__pb2.GetSpeakerColorsRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetSpeakerColorsResponse.FromString,
                _registered_method=True)


class UIServiceServicer(object):
    """UI service (Plugin → Host)
    """

    def ShowNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowDialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPanel(self, request, context):
        """Panel management (Epic 3 / #92)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePanelContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClosePanel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTheme(self, request, context):
        """Theme (Epic 3 Phase 2 / #229)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpeakerColors(self, request, context):
        """Speaker colors (Epic 40 Phase 2)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShowNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowNotification,
                    request_deserializer=plugin__pb2.ShowNotificationRequest.FromString,
                    response_serializer=plugin__pb2.ShowNotificationResponse.SerializeToString,
            ),
            'ShowDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowDialog,
                    request_deserializer=plugin__pb2.ShowDialogRequest.FromString,
                    response_serializer=plugin__pb2.ShowDialogResponse.SerializeToString,
            ),
            'RegisterPanel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPanel,
                    request_deserializer=plugin__pb2.RegisterPanelRequest.FromString,
                    response_serializer=plugin__pb2.RegisterPanelResponse.SerializeToString,
            ),
            'UpdatePanelContent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePanelContent,
                    request_deserializer=plugin__pb2.UpdatePanelContentRequest.FromString,
                    response_serializer=plugin__pb2.UpdatePanelContentResponse.SerializeToString,
            ),
            'ClosePanel': grpc.unary_unary_rpc_method_handler(
                    servicer.ClosePanel,
                    request_deserializer=plugin__pb2.ClosePanelRequest.FromString,
                    response_serializer=plugin__pb2.ClosePanelResponse.SerializeToString,
            ),
            'GetTheme': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTheme,
                    request_deserializer=plugin__pb2.GetThemeRequest.FromString,
                    response_serializer=plugin__pb2.GetThemeResponse.SerializeToString,
            ),
            'GetSpeakerColors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpeakerColors,
                    request_deserializer=plugin__pb2.GetSpeakerColorsRequest.FromString,
                    response_serializer=plugin__pb2.GetSpeakerColorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.UIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.UIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UIService(object):
    """UI service (Plugin → Host)
    """

    @staticmethod
    def ShowNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/ShowNotification',
            plugin__pb2.ShowNotificationRequest.SerializeToString,
            plugin__pb2.ShowNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/ShowDialog',
            plugin__pb2.ShowDialogRequest.SerializeToString,
            plugin__pb2.ShowDialogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPanel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/RegisterPanel',
            plugin__pb2.RegisterPanelRequest.SerializeToString,
            plugin__pb2.RegisterPanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePanelContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/UpdatePanelContent',
            plugin__pb2.UpdatePanelContentRequest.SerializeToString,
            plugin__pb2.UpdatePanelContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClosePanel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/ClosePanel',
            plugin__pb2.ClosePanelRequest.SerializeToString,
            plugin__pb2.ClosePanelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTheme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/GetTheme',
            plugin__pb2.GetThemeRequest.SerializeToString,
            plugin__pb2.GetThemeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpeakerColors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.UIService/GetSpeakerColors',
            plugin__pb2.GetSpeakerColorsRequest.SerializeToString,
            plugin__pb2.GetSpeakerColorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DialogServiceStub(object):
    """Dialog service (Plugin → Host)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentDialog = channel.unary_unary(
                '/parley.plugin.DialogService/GetCurrentDialog',
                request_serializer=plugin__pb2.GetCurrentDialogRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetCurrentDialogResponse.FromString,
                _registered_method=True)
        self.GetSelectedNode = channel.unary_unary(
                '/parley.plugin.DialogService/GetSelectedNode',
                request_serializer=plugin__pb2.GetSelectedNodeRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetSelectedNodeResponse.FromString,
                _registered_method=True)
        self.SelectNode = channel.unary_unary(
                '/parley.plugin.DialogService/SelectNode',
                request_serializer=plugin__pb2.SelectNodeRequest.SerializeToString,
                response_deserializer=plugin__pb2.SelectNodeResponse.FromString,
                _registered_method=True)
        self.GetDialogStructure = channel.unary_unary(
                '/parley.plugin.DialogService/GetDialogStructure',
                request_serializer=plugin__pb2.GetDialogStructureRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetDialogStructureResponse.FromString,
                _registered_method=True)


class DialogServiceServicer(object):
    """Dialog service (Plugin → Host)
    """

    def GetCurrentDialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSelectedNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDialogStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DialogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentDialog,
                    request_deserializer=plugin__pb2.GetCurrentDialogRequest.FromString,
                    response_serializer=plugin__pb2.GetCurrentDialogResponse.SerializeToString,
            ),
            'GetSelectedNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelectedNode,
                    request_deserializer=plugin__pb2.GetSelectedNodeRequest.FromString,
                    response_serializer=plugin__pb2.GetSelectedNodeResponse.SerializeToString,
            ),
            'SelectNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectNode,
                    request_deserializer=plugin__pb2.SelectNodeRequest.FromString,
                    response_serializer=plugin__pb2.SelectNodeResponse.SerializeToString,
            ),
            'GetDialogStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDialogStructure,
                    request_deserializer=plugin__pb2.GetDialogStructureRequest.FromString,
                    response_serializer=plugin__pb2.GetDialogStructureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.DialogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.DialogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DialogService(object):
    """Dialog service (Plugin → Host)
    """

    @staticmethod
    def GetCurrentDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.DialogService/GetCurrentDialog',
            plugin__pb2.GetCurrentDialogRequest.SerializeToString,
            plugin__pb2.GetCurrentDialogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSelectedNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.DialogService/GetSelectedNode',
            plugin__pb2.GetSelectedNodeRequest.SerializeToString,
            plugin__pb2.GetSelectedNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.DialogService/SelectNode',
            plugin__pb2.SelectNodeRequest.SerializeToString,
            plugin__pb2.SelectNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDialogStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.DialogService/GetDialogStructure',
            plugin__pb2.GetDialogStructureRequest.SerializeToString,
            plugin__pb2.GetDialogStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """File service (Plugin → Host)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenFileDialog = channel.unary_unary(
                '/parley.plugin.FileService/OpenFileDialog',
                request_serializer=plugin__pb2.OpenFileDialogRequest.SerializeToString,
                response_deserializer=plugin__pb2.OpenFileDialogResponse.FromString,
                _registered_method=True)
        self.SaveFileDialog = channel.unary_unary(
                '/parley.plugin.FileService/SaveFileDialog',
                request_serializer=plugin__pb2.SaveFileDialogRequest.SerializeToString,
                response_deserializer=plugin__pb2.SaveFileDialogResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/parley.plugin.FileService/ReadFile',
                request_serializer=plugin__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=plugin__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/parley.plugin.FileService/WriteFile',
                request_serializer=plugin__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=plugin__pb2.WriteFileResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """File service (Plugin → Host)
    """

    def OpenFileDialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFileDialog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenFileDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenFileDialog,
                    request_deserializer=plugin__pb2.OpenFileDialogRequest.FromString,
                    response_serializer=plugin__pb2.OpenFileDialogResponse.SerializeToString,
            ),
            'SaveFileDialog': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFileDialog,
                    request_deserializer=plugin__pb2.SaveFileDialogRequest.FromString,
                    response_serializer=plugin__pb2.SaveFileDialogResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=plugin__pb2.ReadFileRequest.FromString,
                    response_serializer=plugin__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=plugin__pb2.WriteFileRequest.FromString,
                    response_serializer=plugin__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parley.plugin.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parley.plugin.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """File service (Plugin → Host)
    """

    @staticmethod
    def OpenFileDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.FileService/OpenFileDialog',
            plugin__pb2.OpenFileDialogRequest.SerializeToString,
            plugin__pb2.OpenFileDialogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveFileDialog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.FileService/SaveFileDialog',
            plugin__pb2.SaveFileDialogRequest.SerializeToString,
            plugin__pb2.SaveFileDialogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.FileService/ReadFile',
            plugin__pb2.ReadFileRequest.SerializeToString,
            plugin__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parley.plugin.FileService/WriteFile',
            plugin__pb2.WriteFileRequest.SerializeToString,
            plugin__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
